### ISSUE TITLE
Playback not working on iOS

### ISSUE THREAD

**Issue by chrishobcroft** [dtube/production#12]
![received_10155567998793212](https://user-images.githubusercontent.com/2212651/37133484-e8c81ba2-2293-11e8-928c-7b9a8f436349.jpeg)

The same message experienced on two separate devices.

**Comment by chrishobcroft** [comment]
https://d.tube/#!/v/chrishobcroft/xtfpi6ay

**Comment by mrdev023** [comment]
What export format did you use for video ?

**Comment by skzap** [comment]
This issue was moved to dtube/embed#15
