### ISSUE TITLE
Slider to skip through content is unusable on Android

### ISSUE THREAD

**Issue by chrishobcroft** [dtube/production#13]
There's no way to drag the slider to a later part of the video.

It kinda works but it's very difficult to know what I have done.

**Comment by chrishobcroft** [comment]
Actually, I've now seen that the slider to skip through the content is there.

So maybe this is not a bug, it's just a different UI than I'm used to at YouTube.

**Comment by skzap** [comment]
Again, this is an embed issue: https://github.com/dtube/embed
