### ISSUE TITLE
A d.tube privacy policy 

### ISSUE THREAD

**Issue by Pope19** [dtube/production#17]
I noticed that d.tube do not have a privacy policy and i decided to create a privacy policy for d.tube.

Privacy policy is a very important document on any website that details a company's views on information collected from visitors and how it intends to secure that information. It also helps to instill more confidence in the prospective site visitors and give users an idea of what to expect and what not to expect on the site.

Here is the proposed privacy policy i drafted for d.tube.

[Proposed D.tube privacy policy](https://paper.dropbox.com/doc/D.TUBE-PRIVACY-POLICY-JevATMoSw0NfTU7ZuHM1Y?openSharing=1)

Please take a look at it for your own personal consideration. All constructive criticism and suggestions are welcomed.

**Comment by chrishobcroft** [comment]
Nice job.

But why do we need it?

**Comment by Pope19** [comment]
Apologies for replying late to your message.

I believe D.tube needs a privacy policy for many reasons some of  which are: 

1. To state your reasons/objectives concerning the information you collect (if any) from your registered Dtube subscribers 

2. If the information obtained is shared with other organization within or outside the Steem-Blockchain or not

3. To clearly state what type of videos/video formats that are acceptable on D.tube e.g videos from other sites, NSFW videos, copyrighted videos etc

4. To state if or whether certain videos can be censored on D.tube

5. To state a clear strong disclaimer, reminding members that they are solely responsible for the videos they post.

6. To improve the user experience of the D.tube visitors, subscribers and end users e.g using cookies to analyze and enhance the interactions of D.tube site visitors, in terms of preferred language settings etc

**Comment by chrishobcroft** [comment]
Thank you for the reply.

What do you mean by "solely largely responsible"?

**Comment by skzap** [comment]
I cannot see the document anymore, link seems to be dead.

This is something we need and we were already working on.

**Comment by Pope19** [comment]
@chrishobcroft 

I meant to say that they are solely responsible for the videos they post on D.tube

**Comment by Pope19** [comment]
@skzap 

[This is the link to the D.tube Privacy Policy](https://paper.dropbox.com/doc/D.TUBE-PRIVACY-POLICY-JevATMoSw0NfTU7ZuHM1Y?openSharing=1)

My Knowledge is limited as to the following: 

1. The type of videos/video formats that are acceptable on D.tube
2. To state if or whether certain videos can be censored on D.tube

The above needs to be added to the main document.

Thank you.

**Comment by skzap** [comment]
Yeah I think the wording is far from perfect. d.tube doesn't store or collect anything apart from uploaded videos for 7 days. 

Technically everything is stored in the local storage (not cookies), in your PC, and is not ever sent through the wire, so it cannot be collected without physical pc access. It stays on the users PC but never gets out (otherwise we would have a security issue as this data contains posting keys). We might want to collect the watch again videos from our users once in a while in the future though...

To wipe the data there are buttons in the UI. For the keys you can just log out, and for the watch again videos there is a 'X' button to delete them when you are in the watch again page, so it's not like people even need to wipe their browser history, that's just a good failsafe.

**Comment by Pope19** [comment]
Thank you for your review.

**Comment by datenbrei** [comment]
Hi there.

The above privacy policy is nowhere visible as a direct link from every page of d.tube. This is a legal requirement in all countries of the EU. Also it's content is not sufficient. Most important things are missing, like the service responsible person or organisation and much much more.

Please have a look in legal documents and requirements: https://gdpr-info.eu/ Ask somebody for help, who has enough knowledge about these legal things. Don't take it as too easy, there are massive penalties possible.

Also: If you host the privacy statement in Dropbox, you also expose users privacy data to them and you need a contract with them.

Hope I could help to fulfill the legal requirements of d.tube.
