### ISSUE TITLE
Control Bar Should Auto-Hide

### ISSUE THREAD

**Issue by chrishobcroft** [dtube/production#18]
When I'm watching video in full screen mode on Android, the control bar stays visible for the entire video, and there's no way to hide this.

If I'm creating beautiful videos and storing in d.tube, then I would like to be able to see the whole thing.

![screenshot_20180313-223251](https://user-images.githubusercontent.com/2212651/37372591-858c81de-2713-11e8-9d90-4d6696ad6728.png)

**Comment by skzap** [comment]
It is supposed to auto hide. Anyway this should be an issue for the embed player. Im not sure why it doesn't auto hide on android. Does it hide if you tap somewhere away from the player? 

I believe it's something easily fixable in the embed if you have an android device to test with.

Feel free to re-open an issue in the appropriate repo: https://github.com/dtube/embed
