### ISSUE TITLE
So Much Same Videos in "Watch Again"

### ISSUE THREAD

**Issue by yussan** [dtube/production#20]
issues : 
i Opened one video on D.Tube and always replay it, when back to the homepage, in "watch again" section, showing the same video many times. like this : 

![screen shot 2018-03-16 at 10 46 37](https://user-images.githubusercontent.com/4264672/37502785-6a83760e-2907-11e8-9d9a-6358d98aa233.png)

Then when i open another video, then thumbnails it be like this.

![screen shot 2018-03-16 at 10 50 10](https://user-images.githubusercontent.com/4264672/37502878-d2f34692-2907-11e8-8e44-f9b704009f11.png)

**Comment by skzap** [comment]
Yes I am aware of this. The bug 'disappears' after you watch a few videos. It's not a major issue, but could be handled better in the app
