### ISSUE TITLE
Enhancement: have subscribe button say subscribed if already following

### ISSUE THREAD

**Issue by kirkins** [dtube/production#23]
I noticed that when I click through from steemit to dlive the subscribe button makes it look like I'm not subscribed.

Example:

![screenshot_20180324-232749](https://user-images.githubusercontent.com/9503662/37871427-8eb86592-2fbb-11e8-84ed-1ee650c4d1aa.png)

**Comment by skzap** [comment]
I cannot reproduce this issue on my end, button is the 'Unfollow' if I'm already following. If this still happens please give more detailed information (such as browser)

**Comment by kirkins** [comment]
Seems to be working for me now.
