### ISSUE TITLE
Failed to reach profile via URL

### ISSUE THREAD

**Issue by tolgahanuzun** [dtube/production#24]
## Expected behavior

I'm opening a user's profile.

- I clicked from somewhere and opened to new tab. The user's profile has been turned on.
- Then I wanted to go to another user via url. I changed the name and clicked enter.
- I've reached another user's profile.

## Actual behavior

I'm opening a user's profile.
- I clicked from somewhere and opened to new tab. The user's profile has been turned on.
- Then I wanted to go to another user via url. I changed the name and clicked enter.
- **Wrong** The page stays by saying it can not be found. Something is not opening.

## How to reproduce
- https://d.tube/#!/c/feronio Enter this adress. Wait for the page to open.
- Come to the url part when it opens. Enter another user. And click.
- You will encounter an error, nothing will come.

Browser: Chrome Version 65.0.3325.162 (Official Build) (64-bit)
Operating system: macOS Sierra

## Recording Of The Bug
![Kapture 2018-03-22 at 18.26.46.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521732603/ypa8o1ndvz9z6hkzdszt.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tolgahanuzun/failed-to-reach-profile-via-url">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by skzap** [comment]
The fragment part of the address bar is technically not part of the url. Feel free to try d.tube/c/username which should work fine
