### ISSUE TITLE
Upload error occurred in mobile(ios with safari)

### ISSUE THREAD

**Issue by mlnl17** [dtube/production#25]
upload from mobile phone.(My phone is Iphone 6s+ and using safari brower)
i tried upload 6-7times.
half ot time failed with “A problem occurred with this webpage so it was reloaded”
massage.

**Comment by skzap** [comment]
How big is the file you are trying to upload?

**Comment by mlnl17** [comment]
i cant remember every previous ones.
but last one occurred error was 1.5GB 13min video.

**Comment by mlnl17** [comment]
after few testing.
first upload attempt occur error always
but second attempt always work.
weird but thats what i experiencing now
