### ISSUE TITLE
Request to run promotion for dtube

### ISSUE THREAD

**Issue by engrbrain1** [dtube/production#27]
I am a true follower of dtube, I would like to contribute also to dtube in a way which i hope will be be fitting to you.
I have a facebook page which I believe can be used to promote dtube with the use of a promotional ad will I will provide.
I want to request your permission before I can carry out the promotion or task. In doing this, I hope to contribute to the dtube community in my own way.

**Comment by wg1929** [comment]
How to modify the gateway because ipfs.io China cannot access

**Comment by wg1929** [comment]
@engrbrain1   How to modify the gateway

**Comment by skzap** [comment]
This has nothing to do with the coding side of DTube. Feel free to reach out on our Discord directly for this type of enquiries
