### ISSUE TITLE
Dtube | EDIT MY PROFIL button does not work

### ISSUE THREAD

**Issue by fadligenta** [dtube/production#30]
#### Expected behavior<br>
Hope Profile edits button works<br>
<br>
#### Actual behavior<br>
The fact that pressing the EDIT MY PROFILE button is always an error.<br>
<br>
#### How to reproduce<br>
<br>
* Browsing on dtube<br>
* Log in with your steemit account <br>
* Please go on your channel <br>
* then click on EDIT  MY PROFILE button<br>
- Device used: Samsung Grand prime SM-G530<br>
<br>
* Operating System: Android version 4.4.4<br>
* BROWSER chrome<br>
<br>
#### Recording Of The Bug<br>
<br>
https://youtu.be/zF4LtBmFY88

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fadligenta/dtube-or-edit-my-profil-button-does-not-work">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by skzap** [comment]
I fixed the display bug on these buttons a bit ago. I tried with iPhone Safari and the bug seems to be gone. Can you confirm it's gone also on your end?
