### ISSUE TITLE
Could not vote: Unknown error

### ISSUE THREAD

**Issue by davidak** [dtube/production#4]
I can't upvote this video or upvote a comment of the user under a video from someone else, where he links to this video.

https://d.tube/#!/v/frmrx/fp61zsq8

JS Console:
```
{error: "server_error",…}
error
:
"server_error"
error_description
:
"10 assert_exception: Assert Exception↵_db.head_block_time() < comment.cashout_time - STEEMIT_UPVOTE_LOCKOUT_HF17: Cannot increase payout within last twelve hours before payout.↵    {}↵    th_a  steem_evaluator.cpp:1223 do_apply↵↵    {"o":{"voter":"davidak","author":"frmrx","permlink":"fp61zsq8","weight":10000}}↵    th_a  steem_evaluator.cpp:1504 do_apply↵↵    {"op":["vote",{"voter":"davidak","author":"frmrx","permlink":"fp61zsq8","weight":10000}]}↵    th_a  database.cpp:2893 _apply_transaction↵↵    {"trx":{"ref_block_num":21840,"ref_block_prefix":2485649968,"expiration":"2018-02-19T16:04:03","operations":[["vote",{"voter":"davidak","author":"frmrx","permlink":"fp61zsq8","weight":10000}]],"extensions":[],"signatures":["1f1e1583fc454e70d8b11e12184cbf53e5da53b582524b27dd68b19f42f23c90647a775963d3595eeba72017ada31d1457fd289c0a403fb5b3621f550"]}}↵    th_a  database.cpp:2897 _apply_transaction↵↵    {"trx":{"ref_block_num":21840,"ref_block_prefix":2485649968,"expiration":"2018-02-19T16:04:03","operations":[["vote",{"voter":"davidak","author":"frmrx","permlink":"fp61zsq8","weight":10000}]],"extensions":[],"signatures":["1f1e1583fc454e70d8b11e12184cbf53e5da53b582524b27dd68b19f42f23c90647a775963d3595eeba72017ada31d1457fd289c0a403fb5b3621f55"]}}↵    th_a  database.cpp:660 push_transaction↵↵    {"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction_synchronous",[{"ref_block_num":21840,"ref_block_prefix":2485649968,"expiration":"2018-02-19T16:04:03","operations":[["vote",{"voter":"davidak","author":"frmrx","permlink":"fp61zsq8","weight":10000}]],"extensions":[],"signatures":["1f1e1583fc454e70d8b11e12184cbf53e5da53b582524b27dd68b19f42f23c90647a775963d3595eeba72017ada31d1457fd289c0a403fb5b3621f55..."]}]]}↵    th_a  websocket_api.cpp:124 on_message"
```

**Comment by skzap** [comment]
The STEEM node seems to return the proper error message here:

> Exception↵_db.head_block_time() < comment.cashout_time - STEEMIT_UPVOTE_LOCKOUT_HF17: Cannot increase payout within last twelve hours before payout.

Believe it or not, this is a feature of the STEEM blockchain, to prevent self-voters who vote at the last moment.

**Comment by skzap** [comment]
I agree the error should properly be formatted on DTube and explain to the user instead of saying a generic 'Blockchain error'

**Comment by davidak** [comment]
Right now i was able to vote on the video. At what time is voting prevented?

Am i really the first person who created an issue here? I can't believe that since the project seams to be already quiet popular. When it is helpful, i can create more issues with things i notice.

**Comment by skzap** [comment]
According to the error message, you wouldn't be able to upvote (only downvote) between 6days+12hours to 7days.

I have just enabled issues recently. The app isn't open source (the rest of our code is), but it's a move in order to start organizing community feedback.
