### ISSUE TITLE
Cropping of IPFS Video into Clips

### ISSUE THREAD

**Issue by chrishobcroft** [dtube/production#6]
I want to publish a video clip which is a cropped version of a video file in IPFS.

For example, if there is a video which is 2hrs long on IPFS, but I want to publish a cropped "clip" from this, I can simply enter:

1. The IPFS hash of the 2hr file
2. The time when the clip should start
3. The time when the clip should end

And I add a title, and I can publish super easily.

For example, if I livestreamed multiple different resolutions (1080p, 720p, 480p, 144p, etc) into IPFS via Livepeer decentralized livestreaming / transcoding platform, then publishing the cropped bits would be really easy.

**Comment by skzap** [comment]
Livepeer gives you a hash ? I have not tested it.

But yeah in theory your idea is doable. I don't really understand the purpose. Doing something like twitch's feature where you can crop a part of your full livestream and export it ?

Surely there has to be a better way to achieve this than making a 'start / end' fields on videos. Can't you take the video file, and crop it with ffmpeg, then ipfs add the resulting file?

**Comment by chrishobcroft** [comment]
OK, I will give an example - using this video clip as an example: https://d.tube/#!/v/chrishobcroft/14j4jzxz

I recently recorded a 2hr long music performance, and stored the whole video file in IPFS.

Now, when I want to publish clips from this 2hr file on DTube, I must do the following:

1. Crop the into smaller clips using local editing software (iMovie)
2. Upload the cropped clip to DTube / IPFS

Here was the output: https://d.tube/#!/v/chrishobcroft/14j4jzxz

This is inefficient in the following ways:

A. It requires me to have local software + skills to use the software.
B. It involves uploading the same content twice, which wastes bandwidth and time.
C. It means that IPFS must store the same content in different forms (the cropped clip + the big file) because IPFS is unable to recognise that this is actually the same video content. This means more cost in filecoin (eventually).

A more elegant solution would be to allow configuration of some more parameters in the "Advanced" uploader / editor to enable:

i) Use the Hash of the 2hr long video (already in IPFS) as the "IPFS Source Video Hash"
ii) Allow publisher to publish a clip which is only a 3.5 minute excerpt from the 2hr clip (see mockup below) starting after e.g. 420 seconds of the 2hr video, and finishing after e.g. 630 seconds of the 2hr video.

![image](https://user-images.githubusercontent.com/2212651/36541870-9e3d28c0-17df-11e8-86b8-6f7d7267a523.png)

This will make it easier and more efficient to publish content on DTube / IPFS, and to remove the requirement to have editing skills / software.

**Comment by chrishobcroft** [comment]
As regards Livepeer:

Livepeer isn't integrated with IPFS, it's a decentralised mechanism for transcoding video from the source format into a number of other formats (720p, 480p, 360p, 144p). It also creates a livestreaming network for live content distribution.

I'm working for the Livepeer project, and it feels like an obvious connection - to use it eventually to livestream content directly into IPFS for storage, and DTube feels like the obvious place.

Kinda like YouTube has "YouTube Live", Livepeer could very easily enable "DTube Live" - see this issue: https://github.com/dtube/production/issues/7

Have a nice day.

**Comment by chrishobcroft** [comment]
Hey, so, I've got another big long file from livestreaming an Ethereum meetup from Berlin.

I want to put straight onto d.tube, but first I must crop them on localhost using badly maintained FOSS with shitty UI.

With this feature described above, I could just upload the content, and crop by configuring where I want the clip to begin / end.

**Comment by chrishobcroft** [comment]
So I cropped and edited the video in iMovie, which was boring, but at least I made something nice:

https://d.tube/#!/v/chrishobcroft/z9s90b3t

**Comment by chrishobcroft** [comment]
Actually, I'm reopening this as a feature request.

In YouTube it allows me to trim and crop videos, and this would make it almost the same.

It's just 2 fields? By default they would be set to 0 and [infinity|EOF]

**Comment by skzap** [comment]
I understand that this can be an interesting feature. However I believe it can create some extra complexity for the users. Also, it will create storage waste as we don't have any process for pinning only a section of a hash/video.

**Comment by chrishobcroft** [comment]
We've all seen the videos where @jbenet plays-back some silly bunny video from IPFS and it plays at #lightning speed without buffering. Well, let's use some of this feature - and show it to the world. Celebrate it.

I am producing a lot of new content these days, and I have in my plans to be able to stream via Livepeer directly into IPFS - so the ability to package a curated set of content would be marvellous, and this would enable it.

It's also a hankering back to the `evil` world of *centralisation*, where YouTube allows me to trim and edit my video clips. They even have a cute little drag-n-drop tool to trim and crop and remove:

![image](https://user-images.githubusercontent.com/2212651/37571622-7a34dee0-2aff-11e8-9ea9-0672ad757f0c.png)

**Comment by Derrick-** [comment]
Because large file data is chunked in IPFS. should it not be relatively easy to create a new parent file that references only certain chunks of the original file?

**Comment by chrishobcroft** [comment]
Thanks @Derrick- for the suggestion.

That would be what I would expect to be very easily possible given the chunking.

I guess the question comes down to how big the chunks are when chunking? And also the data is compressed, so not raw, so, it may need to split chunks into smaller chunks.

How big are the chunks by default?

**Comment by Derrick-** [comment]
It is controllable. There seem to be two predominant methods of chunking, which are normal and trickle. Trickle is activated using the -t option in ipfs add.

 There are other chunking mechanisms available using other command line options.

From a quick look at my own files, Trickle uses 256KB chunks, for the first 174 chunks and then uses 44MB chunks for the rest, where the Normal mode uses 44MB chunks throughout.

I recommend just playing with it and looking at the resultant chunk sizes and counts using:
ipfs ls <hash>
