### ISSUE TITLE
Implement "DTube Live" using Livepeer (analogous to YouTube Live)

### ISSUE THREAD

**Issue by chrishobcroft** [dtube/production#7]
YouTube has "YouTube Live" - which is the livestreaming component.

DTube can have "DTube Live".

It could build on top of Livepeer (http://livepeer.org) decentralised livestreaming platform (kinda like IPFS but for livestreaming instead of storage).

A simple first step MVP implementation could be:

1. Simply allow a DTube account to configure a public Ethereum address where they might be livestreaming using Livepeer.

For example, livepeer.tv is usually broadcasting at https://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014, with Eth address 0x0dDB225031cCB58fF42866f82D907F7766899014

2. If a viewer loads my channel, and I am also streaming live on Livepeer at this Eth address, then it could show that I am LIVE, and also pull in the content using an embeddable iframe created by @jozanza http://gitter.im/jozanza:

`<iframe type="text/html" width="640" height="360" src="https://media.livepeer.org/embed/0x0dDB225031cCB58fF42866f82D907F7766899014" frameborder="0"></iframe>
`

This should be an easy starting point to build.

After this, we can look at getting it integrated so that livestreams get stored in IPFS and published to my DTube channel.

For more information on Livepeer, and Token Bounties, talk to the core team of developers at http://gitter.im/livepeer/dev where we've recently been discussing DTube in terms of transcoding and livestreaming. Also, leading some of Livepeer's core video implementations is @j0sh http://gitter.im/j0sh

Or you can talk directly to me at http://gitter.im/chrishobcroft or @chrishobcroft :)

**Comment by Katamori** [comment]
I afraid with the existence of [DLive](https://dlive.io) it would 1: be redundant, 2: **and** pose comparably unnecessary development burden on @skzap 's behalf.

**Comment by watchcoin** [comment]
D.Live is currently running on Wowza's centralised video streaming platform. There is nothing decentralised about it. It would take them some time to migrate to Livepeer.

If D.Tube adds a new field to User called {ETHAddress}, and then embeds some iframes in some web views, then you have D.Tube Live.

<iframe type="text/html" width="1920" height="1080" src="https://media.livepeer.org/embed/{ETHAddress}" frameborder="0"></iframe>

The project has done all the hard work, led by @jozanza

It should be nearly-zero development burden to introduce D.Tube Live.

**Comment by chrishobcroft** [comment]
Hi @skzap, how are you? Great work you're doing with d.tube.

At Livepeer TV, we are using d.tube to show archive footage from livestreams at www.livepeer.tv. Take a look for yourself at http://archive.livepeer.tv

Livepeer's video streaming protocol is also launching soon on Ethereum Blockchain
