### ISSUE TITLE
Read-only APIs Documentation?

### ISSUE THREAD

**Issue by weatherman2095pro** [dtube/production#8]
There seems to be no documentation readily available for dtube APIs, so I've tried to make do with what I've found in code.

I've been having trouble with sending a get request to urls such as `https://d.tube/oembed?format=json&url=https%3A%2F%2Fd.tube%2Fv%2Ffrench.fyde%2Fbn8o5sli` or `https://d.tube/services/oembed?format=json&url=https%3A%2F%2Fd.tube%2Fv%2Ffrench.fyde%2Fbn8o5sli` as I get a redirect to `/#!/oembed`.

Trying similar calls while assuming `/#!/oembed` to be the proper endpoint failed to get any useful results. In fact, it returns the normal browser-oriented page content instead of json.

So either I'm noticing a broken API or I'm calling something which doesn't exist. Both problems would be easier diagnosed with proper documentation.

**Comment by skzap** [comment]
I only recently created the endpoint for oembed support. It's on https://api.d.tube/oembed
The repository that powers it is here : https://github.com/dtube/oembedtube

Example: https://api.d.tube/oembed?url=https://d.tube/v/benswann/zqd630em

If you want more access to our data than the oembed, I invite you to try to use https://github.com/steemit/steem-js, this is also what our app uses to retrieve and post content on the STEEM blockchain.

**Comment by weatherman2095pro** [comment]
For my current uses the oembed endpoint provides enough data to get started.

I might take a longer look at the STEEM API later on, I have a feeling it might prove helpful.
